version: 1.3.0.{build}
image: Visual Studio 2019
skip_non_tags: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

before_build:
  - ps: >-
      nuget restore

build:
  project: C:\projects\botbone\BotBone.Core\BotBone.Core.csproj
  publish_nuget: true

configuration: Release

after_build:
  - nuget pack -Prop Configuration=Release BotBone.Core -OutputDirectory BotBone.Core/bin/Release/

artifacts:
  - path: '**\*.nupkg'
    name: BotBone

deploy:
  - provider: NuGet
    api_key:
      # Use encrypt tool
      # https://ci.appveyor.com/tools/encrypt
      secure: 0p+A7xhW2Qex9C3sIr4LXPFBNUCxVd1NPvnKH0Yy6uETIpnSAa5q/DkQtOH9Sy9q
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    artifact: /.*\.nupkg/ # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    description: |
      これは BotBone Plugin 開発者用APIライブラリです。動作する BotBone 本体ではありません。

      ## 1.3.0
      ### Plugin API

      BotBone 起動時に有効化されるプラグインを実装できるようになりました。
      モジュールやコマンドと異なり、起動時にアクティベートされるだけなので、
      裏でロジックを動作させる、イベントを購読するなどの目的を想定しています。

    auth_token:
      secure: oUjl9upjQlUJAOdq7XeHbax8LSo0lUuRRB91g2ROG/Q2MX8Khv7OnB2ZQRa8AIWD
    on:
      APPVEYOR_REPO_TAG: true # deploy on tag push only
